require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ParticipacaoProjetosController do

  def mock_participacao_projeto(stubs={})
    @mock_participacao_projeto ||= mock_model(ParticipacaoProjeto, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all participacao_projetos as @participacao_projetos" do
      ParticipacaoProjeto.stub(:all) { [mock_participacao_projeto] }
      get :index
      assigns(:participacao_projetos).should eq([mock_participacao_projeto])
    end
  end

  describe "GET show" do
    it "assigns the requested participacao_projeto as @participacao_projeto" do
      ParticipacaoProjeto.stub(:find).with("37") { mock_participacao_projeto }
      get :show, :id => "37"
      assigns(:participacao_projeto).should be(mock_participacao_projeto)
    end
  end

  describe "GET new" do
    it "assigns a new participacao_projeto as @participacao_projeto" do
      ParticipacaoProjeto.stub(:new) { mock_participacao_projeto }
      get :new
      assigns(:participacao_projeto).should be(mock_participacao_projeto)
    end
  end

  describe "GET edit" do
    it "assigns the requested participacao_projeto as @participacao_projeto" do
      ParticipacaoProjeto.stub(:find).with("37") { mock_participacao_projeto }
      get :edit, :id => "37"
      assigns(:participacao_projeto).should be(mock_participacao_projeto)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created participacao_projeto as @participacao_projeto" do
        ParticipacaoProjeto.stub(:new).with({'these' => 'params'}) { mock_participacao_projeto(:save => true) }
        post :create, :participacao_projeto => {'these' => 'params'}
        assigns(:participacao_projeto).should be(mock_participacao_projeto)
      end

      it "redirects to the created participacao_projeto" do
        ParticipacaoProjeto.stub(:new) { mock_participacao_projeto(:save => true) }
        post :create, :participacao_projeto => {}
        response.should redirect_to(participacao_projeto_url(mock_participacao_projeto))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved participacao_projeto as @participacao_projeto" do
        ParticipacaoProjeto.stub(:new).with({'these' => 'params'}) { mock_participacao_projeto(:save => false) }
        post :create, :participacao_projeto => {'these' => 'params'}
        assigns(:participacao_projeto).should be(mock_participacao_projeto)
      end

      it "re-renders the 'new' template" do
        ParticipacaoProjeto.stub(:new) { mock_participacao_projeto(:save => false) }
        post :create, :participacao_projeto => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested participacao_projeto" do
        ParticipacaoProjeto.stub(:find).with("37") { mock_participacao_projeto }
        mock_participacao_projeto.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :participacao_projeto => {'these' => 'params'}
      end

      it "assigns the requested participacao_projeto as @participacao_projeto" do
        ParticipacaoProjeto.stub(:find) { mock_participacao_projeto(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:participacao_projeto).should be(mock_participacao_projeto)
      end

      it "redirects to the participacao_projeto" do
        ParticipacaoProjeto.stub(:find) { mock_participacao_projeto(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(participacao_projeto_url(mock_participacao_projeto))
      end
    end

    describe "with invalid params" do
      it "assigns the participacao_projeto as @participacao_projeto" do
        ParticipacaoProjeto.stub(:find) { mock_participacao_projeto(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:participacao_projeto).should be(mock_participacao_projeto)
      end

      it "re-renders the 'edit' template" do
        ParticipacaoProjeto.stub(:find) { mock_participacao_projeto(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested participacao_projeto" do
      ParticipacaoProjeto.stub(:find).with("37") { mock_participacao_projeto }
      mock_participacao_projeto.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the participacao_projetos list" do
      ParticipacaoProjeto.stub(:find) { mock_participacao_projeto }
      delete :destroy, :id => "1"
      response.should redirect_to(participacao_projetos_url)
    end
  end

end
