require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe VinculosController do

  def mock_vinculo(stubs={})
    @mock_vinculo ||= mock_model(Vinculo, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all vinculos as @vinculos" do
      Vinculo.stub(:all) { [mock_vinculo] }
      get :index
      assigns(:vinculos).should eq([mock_vinculo])
    end
  end

  describe "GET show" do
    it "assigns the requested vinculo as @vinculo" do
      Vinculo.stub(:find).with("37") { mock_vinculo }
      get :show, :id => "37"
      assigns(:vinculo).should be(mock_vinculo)
    end
  end

  describe "GET new" do
    it "assigns a new vinculo as @vinculo" do
      Vinculo.stub(:new) { mock_vinculo }
      get :new
      assigns(:vinculo).should be(mock_vinculo)
    end
  end

  describe "GET edit" do
    it "assigns the requested vinculo as @vinculo" do
      Vinculo.stub(:find).with("37") { mock_vinculo }
      get :edit, :id => "37"
      assigns(:vinculo).should be(mock_vinculo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created vinculo as @vinculo" do
        Vinculo.stub(:new).with({'these' => 'params'}) { mock_vinculo(:save => true) }
        post :create, :vinculo => {'these' => 'params'}
        assigns(:vinculo).should be(mock_vinculo)
      end

      it "redirects to the created vinculo" do
        Vinculo.stub(:new) { mock_vinculo(:save => true) }
        post :create, :vinculo => {}
        response.should redirect_to(vinculo_url(mock_vinculo))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vinculo as @vinculo" do
        Vinculo.stub(:new).with({'these' => 'params'}) { mock_vinculo(:save => false) }
        post :create, :vinculo => {'these' => 'params'}
        assigns(:vinculo).should be(mock_vinculo)
      end

      it "re-renders the 'new' template" do
        Vinculo.stub(:new) { mock_vinculo(:save => false) }
        post :create, :vinculo => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vinculo" do
        Vinculo.stub(:find).with("37") { mock_vinculo }
        mock_vinculo.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :vinculo => {'these' => 'params'}
      end

      it "assigns the requested vinculo as @vinculo" do
        Vinculo.stub(:find) { mock_vinculo(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:vinculo).should be(mock_vinculo)
      end

      it "redirects to the vinculo" do
        Vinculo.stub(:find) { mock_vinculo(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(vinculo_url(mock_vinculo))
      end
    end

    describe "with invalid params" do
      it "assigns the vinculo as @vinculo" do
        Vinculo.stub(:find) { mock_vinculo(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:vinculo).should be(mock_vinculo)
      end

      it "re-renders the 'edit' template" do
        Vinculo.stub(:find) { mock_vinculo(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vinculo" do
      Vinculo.stub(:find).with("37") { mock_vinculo }
      mock_vinculo.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the vinculos list" do
      Vinculo.stub(:find) { mock_vinculo }
      delete :destroy, :id => "1"
      response.should redirect_to(vinculos_url)
    end
  end

end
